# Generated by Django 3.2.13 on 2022-06-01 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorId', models.CharField(max_length=100)),
                ('authorResidence', models.CharField(max_length=100)),
                ('communtId', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('contentId', models.CharField(max_length=100)),
                ('source', models.CharField(default='', max_length=100)),
                ('timestamp', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communityId', models.UUIDField()),
                ('highQuality', models.FloatField()),
                ('content', models.TextField()),
                ('pattern', models.FloatField()),
                ('popularity', models.FloatField()),
                ('random', models.FloatField()),
                ('timelines', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Interactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(default='', max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('eventType', models.CharField(choices=[('LIKE', 'LIKE'), ('VIEW', 'VIEW'), ('UNCOMMENT', 'UNCOMMENT'), ('FOLLOW', 'FOLLOW'), ('UNFOLLOW', 'UNFOLLOW'), ('DISLIKE', 'DISLIKE'), ('REACT-POSITIVE', 'REACT-POSITIVE'), ('REACT-NEGATIVE', 'REACT-NEGATIVE'), ('COMMENT-BEST-POSITIVE', 'COMMENT-BEST-POSITIVE'), ('COMMENT-AVERAGE-POSITIVE', 'COMMENT-AVERAGE-POSITIVE'), ('COMMENT-GOOD-POSITIVE', 'COMMENT-GOOD-POSITIVE'), ('COMMENT-BEST-NEGATIVE', 'COMMENT-BEST-NEGATIVE'), ('COMMENT-AVERAGE-NEGATIVE', 'COMMENT-AVERAGE-NEGATIVE'), ('COMMENT-GOOD-NEGATIVE', 'COMMENT-GOOD-NEGATIVE')], default='', max_length=100)),
                ('communityId', models.CharField(max_length=100)),
                ('source', models.CharField(default='', max_length=100)),
                ('timestamp', models.IntegerField(default=0)),
                ('contentId', models.ForeignKey(db_column='contentId', on_delete=django.db.models.deletion.CASCADE, to='articleRecommender.article')),
            ],
            options={
                'ordering': ['timestamp'],
                'unique_together': {('userId', 'contentId', 'eventType')},
            },
        ),
    ]
